name: Perform tests

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github ./src
      continue-on-error: false
    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint --rcfile=./.pylintrc ./src/*
      continue-on-error: false
    - name: Type check with MyPy
      run: |
        pip install mypy
        mypy --config-file=mypy.ini ./src
      continue-on-error: false
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
